global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
rule_files:
- /etc/config/recording_rules.yml
- /etc/config/alerting_rules.yml
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- job_name: 'go-metrics'
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_service_name
    regex: default;sample-go-app-service
    action: keep
  - source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_pod_container_port_number
    regex: default;2112
    action: keep
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: job
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
